### ISSUE TITLE
Merging branch test and code branch for a new PR

### ISSUE THREAD

**Issue by araza6** [qgrad/qgrad#30]
I have been developing qutip functions in a separate PR https://github.com/qgrad/qgrad/pull/22 and its tests in a separate PR https://github.com/qgrad/qgrad/pull/18. 

In order to run import all `qgrad.qutip` functions to run pytest, I need all the new code in one single branch. Should I just `git pull origin <either-of-the-two-branches>` to another, or should I open a new pull request with all the code there together?

@nathanshammah @quantshah

**Comment by nathanshammah** [comment]
It often happens that one has some code waiting to be merged that is needed in another PR.

The usual way I do this is to wait for one PR to be merged and then address the other one, importing them with a local master update and then merging master to the branch of the second, outstanding PR. 

Otherwise you can implement the changes in the second PR from the first one, but that may make "diff'ing" for PR review harder, as those changes will be present in the second PR and conflicts may arise. 

The option of merging into one single PR is the least advisable one in general. However, since the tests in #18 refer to the same functions of #22 (or include them), to me that would be acceptable. In general tests should come along in the same PR of the functions.
